version: "2"
linters:
  default: none
  enable:
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 120
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - exitAfterDefer
        - whyNoLint
        - singleCaseSwitch
        - commentedOutCode
        - appendAssign
        - octalLiteral
        - preferWriteByte
        - httpNoBody
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: //go:generate
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocognit
          - goconst
          - gocyclo
          - gosec
          - lll
          - scopelint
        path: _test\.go
      - linters:
          - govet
        text: declaration of "(err|ctx|log)"
      - linters:
          - funlen
          - gocognit
          - goconst
          - gocyclo
        path: cmd\/.+\/main\.go
      - path: cmd\/.+\/main\.go
        text: G(307|304)
      - linters:
          - revive
        text: 'if-return: redundant if ...; err != nil check, just return error instead.'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/gotd/
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
